imports:
  ssh: ../ssh/enumerate.yml
  ftp: ../ftp/enumerate.yml
types:
  NetworkApplication:
    enum:
      - SSH
      - FTP
  NetworkApplicationEnumerateDetails:
    union:
      SSHEnumerateDetails: ssh.SSHEnumerateDetails
      FTPEnumerateDetails: ftp.FTPEnumerateDetails
  NetworkApplicationEnumerateReport:
    properties:
      targets: list<string>
      details: optional<list<NetworkApplicationEnumerateDetails>>
      errors: optional<list<string>>
