imports:
  common: ../common/common.yml
types:
  ServiceDetails:
    properties:
      host: string
      ip: string
      port: integer
      tls: boolean
      version: string
      transport: common.TransportType
      protocol: common.ProtocolType
      metadata: optional<map<string, string>>
  DiscoverServiceConfig:
    properties:
      target: string
      port: integer
      timeout: integer
  DiscoverServiceResult:
    properties:
      services: optional<list<ServiceDetails>>
  DiscoverServiceReport:
    properties:
      config: DiscoverServiceConfig
      result: DiscoverServiceResult
      errors: optional<list<string>>
