imports:
  common: ../common/common.yml
types:
  ServiceFingerprint:
    properties:
      host: string
      ip: string
      port: integer
      tls: boolean
      version: string
      transport: common.TransportType
      protocol: common.ProtocolType
      metadata: optional<map<string, string>>
  ServiceFingerprintReport:
    properties:
      target: string
      serviceFingerprints: optional<list<ServiceFingerprint>>
      errors: optional<list<string>>
