name: 🙏🏻 Verify

on:
  workflow_call:
  push:
    branches:
      - develop

jobs:
  verify:
    name: Verify
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install -y libpcap-dev

      - name: Generate Fern Go Code
        run: |
          npm install -g fern-api
          fern generate --group local
        env:
          FERN_TOKEN: ${{ secrets.FERN_TOKEN }}

      - name: Godel Verify
        run: ./godelw verify
